#!/usr/bin/env python3
"""
Patch bias descriptions with curated 2-sentence definitions.
Run: python3 patch_bias_descriptions.py
"""
import json
from pathlib import Path

DATA_FILE = Path(__file__).parent / "user_provided_codex" / "biases.json"

# Curated 2-sentence descriptions for all 169 biases
DESCRIPTIONS = {
    "Information overload": "The state of having too much information to make a good decision or keep up with events. It causes people to filter out even relevant information and leads to poorer-quality decisions.",
    "Availability heuristic": "A mental shortcut where people judge the likelihood of events by how easily examples come to mind. Vivid or recent events are recalled more readily, causing their frequency or risk to be overestimated.",
    "Attentional bias": "The tendency to pay more attention to emotionally dominant stimuli while ignoring other relevant information. It can skew perception, memory, and judgment by over-weighting whatever grabs our focus.",
    "Illusory truth effect": "Repeated exposure to a statement increases our belief that it is true, regardless of its actual accuracy. This happens because familiarity is unconsciously mistaken for truth.",
    "Mere exposure effect": "People develop a preference for things simply because they are familiar with them. More exposure to a stimulus leads to greater liking, even without conscious awareness.",
    "Context effect": "The context or environment in which something is experienced influences how it is perceived and remembered. The same information can be interpreted very differently depending on surrounding cues.",
    "Frequency illusion": "Once you notice something for the first time, you start seeing it everywhere. This is because attention and pattern-matching systems are newly primed to detect it, not because its frequency has increased.",
    "Empathy gap": "The tendency to underestimate the influence of visceral emotional states on our own attitudes and behaviour. People in a 'cold' state cannot accurately predict how they'll think or act in a 'hot' emotional state.",
    "Omission bias": "The tendency to judge harmful actions as worse than equally harmful inactions. People prefer doing nothing over actively causing harm, even when inaction leads to the same or greater damage.",
    "Base rate fallacy": "The tendency to ignore general statistical information and focus on specific case information when making judgments. Individual details feel more compelling than broad probability data.",
    "Bizarreness effect": "Bizarre or unusual material is more easily remembered than common material. The novelty of a strange item makes it stand out and be encoded more distinctly in memory.",
    "Von Restorff effect": "An item that stands out from its peers is more likely to be remembered. The isolation effect occurs because distinctiveness captures attention and aids memory encoding.",
    "Picture superiority effect": "Concepts that are learned by viewing pictures are more easily recalled than concepts learned by reading words. Visual processing engages more memory systems simultaneously.",
    "Self-relevance effect": "Information relating to oneself is remembered better than other types of information. Personal relevance triggers deeper processing, creating stronger memory traces.",
    "Negativity bias": "Negative events and information receive more attention and have greater psychological impact than neutral or positive things of equal intensity. Losses loom larger than equivalent gains.",
    "Anchoring": "The tendency to rely too heavily on the first piece of information encountered when making decisions. Subsequent estimates are then adjusted from this initial anchor, often insufficiently.",
    "Money illusion": "The tendency to think of currency in nominal rather than real terms, ignoring the effect of inflation. People focus on the face value of money rather than its actual purchasing power.",
    "Framing effect": "People react differently to a choice depending on whether it is presented as a loss or a gain. The same outcome described in different ways leads to different decisions.",
    "WeberFechner law": "The perceived difference between two stimuli is proportional to the magnitude of the stimuli, not their absolute difference. A small change in a large stimulus is less noticeable than in a small one.",
    "Conservatism": "The tendency to revise one's beliefs insufficiently when presented with new evidence. People under-update their prior beliefs even when confronted with strong contradicting information.",
    "Distinction bias": "When comparing two options side by side, people place more importance on differences than when they evaluate each option individually. Joint evaluation magnifies perceived differences.",
    "Confirmation bias": "The tendency to search for, interpret, favor, and recall information in a way that confirms one's pre-existing beliefs. Disconfirming evidence is discounted or ignored.",
    "Congruence bias": "The tendency to test hypotheses exclusively through direct testing rather than testing alternative hypotheses. People repeatedly test one explanation without considering others.",
    "Post-purchase rationalization": "After making a decision, people tend to rationalize it as having been correct, regardless of the actual evidence. This reduces cognitive dissonance by convincing ourselves the choice was good.",
    "Choice-supportive bias": "The tendency to retroactively attribute positive features to options we have chosen and negative features to options we rejected. We misremember our choices as better than they were.",
    "Selective perception": "The tendency to perceive what we expect to perceive and to filter out information that contradicts our expectations. Perception is shaped by existing attitudes and beliefs.",
    "Observer-expectancy effect": "When a researcher expects a given result, they may unconsciously manipulate an experiment or misinterpret data to find it. Expectations bias the observation process itself.",
    "Ostrich effect": "The tendency to ignore dangerous or negative information by 'burying one's head in the sand.' People avoid monitoring situations likely to deliver bad news.",
    "Subjective validation": "The tendency to perceive two unrelated events as connected because a belief, expectation, or hypothesis demands a relationship. Personal validation makes weak connections feel meaningful.",
    "Continued influence effect": "The tendency to continue believing in information even after it has been corrected. Misinformation continues to influence memory and reasoning even when a correction is explicitly acknowledged.",
    "Semmelweis reflex": "The reflexive tendency to reject new information that contradicts established norms, paradigms, or beliefs. Novel discoveries are dismissed without fair consideration.",
    "Bias blind spot": "The tendency to see oneself as less biased than other people. We recognize cognitive biases in others far more easily than in our own thinking.",
    "Naive cynicism": "The expectation that others are more cynically self-interested than they actually are. People assume others have more selfish motives than they themselves do.",
    "Naive realism": "The belief that we see the world objectively, and that others who disagree are uninformed, irrational, or biased. We trust our own perceptions as direct access to reality.",
    "Confabulation": "The spontaneous production of fabricated, distorted, or misinterpreted memories without the conscious intention to deceive. The brain fills memory gaps with plausible-sounding but incorrect information.",
    "Clustering illusion": "The tendency to see patterns in random data, especially clusters of similar events. Our brains are wired to find structure even when none exists.",
    "Insensitivity to sample size": "The tendency to underestimate the variability of small samples and treat them as representative of larger populations. Small samples produce more extreme results by chance.",
    "Neglect of probability": "The tendency to completely disregard probability when making decisions under uncertainty. Very small or very large probabilities are often treated as zero or one.",
    "Anecdotal fallacy": "The tendency to give too much credence to personal stories and anecdotes over statistical evidence. One vivid example feels more persuasive than large-scale data.",
    "Illusion of validity": "The tendency to believe that additional information generates additional relevant data for predictions, even when it doesn't. Confidence in a prediction exceeds what the evidence warrants.",
    "Masked man fallacy": "Assuming that identical descriptions always refer to the same thing, even in intensional contexts where identity depends on how something is described. A logical error in substituting co-referential terms.",
    "Recency illusion": "The belief that something is a new phenomenon when in fact it has existed for a long time. People mistakenly assume the first time they noticed something is when it first appeared.",
    "Gamblers fallacy": "The mistaken belief that if a random event has occurred more frequently than normal recently, it is less likely to happen in the future. Past random events do not influence future ones.",
    "Hot-hand fallacy": "The belief that a person who has experienced success with a random event has a greater chance of further success in subsequent attempts. Streaks in random processes are misread as skill.",
    "Illusory correlation": "The tendency to perceive a relationship between two variables when no such relationship exists. People see patterns that fit preexisting expectations even in random data.",
    "Pareidolia": "The tendency to perceive a familiar pattern where none exists, such as seeing faces in clouds or hearing words in noise. The brain's pattern recognition systems are hyperactive.",
    "Anthropomorphism": "The attribution of human characteristics, emotions, and intentions to non-human entities. People naturally apply their social cognition to animals, objects, and even abstract forces.",
    "Group attribution error": "The tendency to believe that the decisions and actions of a group reflect the preferences of all individual group members. Individual variation within the group is ignored.",
    "Ultimate attribution error": "A group-level version of the fundamental attribution error, where positive actions by out-group members are attributed to external factors and negative actions to internal character. In-group behavior receives the opposite treatment.",
    "Stereotyping": "The expectation that a member of a group will have certain characteristics without actually knowing the individual. Stereotypes can be inaccurate and overly generalized representations.",
    "Essentialism": "The attribution of a fixed, underlying essence or nature to categories of people or things. People believe categories have intrinsic defining properties rather than being socially constructed.",
    "Functional fixedness": "The tendency to see objects only in the way they are traditionally used, limiting creative problem-solving. A hammer is seen only as a hammer, not as a paperweight or lever.",
    "Moral credential effect": "When past moral behaviour gives people license to do less moral things in the future. Having established a virtuous track record, people feel they have earned the right to act selfishly.",
    "Just-world hypothesis": "The belief that the world is fundamentally just and that people get what they deserve. This leads to blaming victims of misfortune for their own circumstances.",
    "Argument from fallacy": "The assumption that if an argument contains a logical fallacy, its conclusion must be false. A flawed argument does not automatically make the conclusion wrong.",
    "Authority bias": "The tendency to attribute greater accuracy to the opinion of an authority figure and be more influenced by their views. Status and credentials are equated with correctness.",
    "Automation bias": "The tendency to over-rely on automated systems and accept their output without sufficient critical evaluation. People trust machine recommendations more than their own judgment.",
    "Bandwagon effect": "The tendency to adopt beliefs and behaviours because many other people do so. Popularity serves as a proxy for correctness or desirability.",
    "Placebo effect": "A beneficial effect produced by a treatment that cannot be attributed to the treatment's properties but must be attributed to the patient's belief in the treatment. Expectation creates measurable physiological change.",
    "Halo effect": "The tendency for an overall impression of a person to influence specific evaluations of their qualities. A positive general impression causes specific attributes to be rated higher than warranted.",
    "In-group bias": "The tendency to favour members of one's own group over those in other groups. People give preferential treatment, resources, and positive evaluations to in-group members.",
    "Out-group homogeneity bias": "The tendency to perceive members of an out-group as more similar to each other than in-group members are to each other. 'They all look the same' while 'we are individuals.'",
    "Cross-race effect": "The tendency to recognise faces of one's own racial group more accurately than faces of other racial groups. Experience and exposure shape facial recognition patterns.",
    "Cheerleader effect": "The tendency for people to appear more attractive when they are in a group than when alone. Averaging out individual features against a group creates a more appealing composite impression.",
    "Well-traveled road effect": "The tendency to underestimate the travel time for frequently travelled routes and overestimate it for infrequently travelled routes. Familiarity reduces perceived duration.",
    "Not invented here": "The tendency to avoid using or buying already existing products, research, standards, or knowledge because of their external origins. In-group pride leads to rejection of outside solutions.",
    "Reactive devaluation": "The tendency to devalue concessions made by an opponent simply because the opponent has made them. A proposal from an adversary is automatically viewed as less attractive.",
    "Positivity effect": "The tendency for older adults to recall positive memories more readily than negative ones. Emotional memory becomes more selective in favour of positive content with age.",
    "Mental accounting": "The tendency to treat money differently depending on its source or intended use, rather than treating all money as fungible. 'Found' money is spent more freely than earned money.",
    "Normalcy bias": "The tendency to underestimate the possibility of a disaster and its effects. People believe things will always function as they normally have, making preparation for crises inadequate.",
    "Appeal to probability fallacy": "The assumption that because something could happen, it will inevitably happen. Possibility is confused with certainty.",
    "Murphys Law": "The popular belief that anything that can go wrong will go wrong, and at the worst possible time. While not a formal bias, it reflects a general expectation of bad outcomes that can become self-fulfilling.",
    "Subadditivity effect": "The tendency to judge the probability of the whole to be less than the probabilities of its parts. Disaggregating an event into components makes each component seem individually more likely.",
    "Survivorship bias": "The logical error of focusing on the people or things that 'survived' some process while overlooking those that did not. Only visible successes are studied, ignoring the invisible failures.",
    "Zero sum bias": "The tendency to think that situations are zero-sum when they are not, meaning one person's gain is seen as another's loss. Cooperative positive-sum outcomes are underappreciated.",
    "Denomination effect": "The tendency to spend more money when using small denominations than when using large ones. A large bill feels more 'real' as money than an equivalent pile of coins or small notes.",
    "Magic number 7+-2": "The observation that the number of objects an average human can hold in working memory is approximately seven, plus or minus two. This limits information processing capacity.",
    "Curse of knowledge": "When better-informed people find it extremely difficult to think about problems from the perspective of less-informed people. Experts forget what it was like not to know what they know.",
    "Illusion of transparency": "The tendency to overestimate the degree to which one's mental state is known to others. People believe their inner thoughts and feelings are more visible than they actually are.",
    "Spotlight effect": "The tendency to overestimate how much other people notice aspects of one's appearance or behavior. People feel more 'on stage' than they actually are.",
    "Illusion of external agency": "The tendency to attribute personally generated outcomes to external sources. Random events or self-created patterns are mistakenly perceived as caused by an outside force.",
    "Illusion of asymmetric insight": "The belief that one understands others better than others understand oneself. People feel they see through others while remaining opaque themselves.",
    "Extrinsic incentive error": "The tendency to attribute others' motivations to extrinsic factors while attributing one's own motivations to intrinsic factors. We think we are driven by passion; others are driven by money.",
    "Hindsight bias": "The tendency, after an event has occurred, to see it as having been predictable all along. 'I knew it would happen' is a common post-hoc distortion.",
    "Outcome bias": "The tendency to judge a decision by its eventual outcome rather than by the quality of the decision at the time it was made. A bad decision that leads to a good outcome is rated as a good decision.",
    "Moral luck": "The tendency to assign praise or blame for outcomes that were substantially influenced by factors beyond the agent's control. Luck is confused with character.",
    "Declinism": "The predisposition to view the past more favourably and the future more negatively. People overestimate how much things have worsened and underestimate progress.",
    "Telescoping effect": "The tendency to displace recent events further into the past and remote events into the more recent past. Events from several years ago feel as though they happened recently, or vice versa.",
    "Rosy retrospection": "The tendency to rate past events more positively in memory than they were rated at the time they occurred. Memories are sanitized over time, leaving a rosier impression.",
    "Impact bias": "The tendency to overestimate the emotional impact of future events on one's long-term wellbeing. We think we will feel much better or worse than we actually will.",
    "Pessimism bias": "The tendency to overestimate the likelihood of negative outcomes and underestimate the likelihood of positive ones. The opposite of optimism bias, it leads to unwarranted gloom.",
    "Planning fallacy": "The tendency to underestimate the time, costs, and risks of future actions while overestimating the benefits. Projects almost always take longer and cost more than planned.",
    "Time-saving bias": "The tendency to underestimate the time saved by increasing the speed of a slow mode of transportation. Small speed increases at low speeds are overvalued relative to large speed increases at high speeds.",
    "Pro-innovation bias": "The tendency for an innovation's proponents to overestimate its usefulness and underestimate its limitations and weaknesses. New technologies are assumed to be beneficial by default.",
    "Projection bias": "The tendency to falsely project current preferences onto the future self. We assume our future selves will want, feel, and value what we currently want, feel, and value.",
    "Restraint bias": "The tendency to overestimate one's ability to control impulsive behaviour. Overconfidence in self-control leads to unnecessary exposure to temptation.",
    "Self-consistency bias": "The tendency to remember past attitudes, beliefs, and behaviours as more consistent with one's current attitudes than they actually were. We revise memory to maintain a consistent self-narrative.",
    "Overconfidence effect": "The tendency for a person's subjective confidence in their judgements to be greater than the objective accuracy of those judgements. People know less than they think they do.",
    "Egocentric bias": "The tendency to rely too heavily on one's own perspective when considering the viewpoints of others, or to give a disproportionately large amount of credit for collaborative work. The self is the default reference point.",
    "Optimism bias": "The tendency to overestimate the likelihood of positive events and underestimate the likelihood of negative events in one's own future. 'It won't happen to me.'",
    "Social desirability bias": "The tendency to respond to survey questions in a way that will be viewed favourably by others rather than giving truthful answers. People present themselves as more socially acceptable than they are.",
    "Third-person effect": "The belief that others are more influenced by mass media messages than oneself. 'Propaganda works on them, not on me.'",
    "Barnum effect": "The tendency to accept vague, general personality descriptions as uniquely applicable to oneself. Horoscopes feel personally accurate because they apply to almost anyone.",
    "Illusion of control": "The tendency to believe one can control or at least influence outcomes that are actually determined by chance. People act as if skill influences purely random events.",
    "False consensus effect": "The tendency to overestimate the degree to which one's own opinions, attitudes, and behaviours are shared by others. 'Most people think the way I do.'",
    "Dunning-Kruger effect": "People with limited competence in a domain tend to overestimate their own ability, while highly competent people tend to underestimate their ability. Low skill comes with insufficient self-awareness.",
    "Hard-easy effect": "The tendency to overestimate success rates on hard tasks and underestimate success on easy tasks. Calibration is poor at both extremes of difficulty.",
    "Illusory superiority": "The tendency to overestimate one's own qualities and abilities relative to others. Most people rate themselves as above average on desirable traits.",
    "Lake Wobegone effect": "The tendency for most people to consider themselves above average in desirable qualities. Named after the fictional town where 'all the children are above average.'",
    "Self-serving bias": "The tendency to attribute positive events to one's own character and negative events to external factors. Success is due to talent; failure is due to bad luck.",
    "Fundamental attribution error": "The tendency to overemphasize dispositional (character-based) explanations for behaviour and underemphasize situational explanations. We see people's actions as reflecting who they are, not where they are.",
    "Defensive attribution hypothesis": "The tendency to attribute more blame to a perpetrator as the outcome of an accident becomes more severe, regardless of the perpetrator's actual level of fault. Severity of harm drives blame.",
    "Trait ascription bias": "The tendency for people to view themselves as relatively variable in terms of personality and behaviour while viewing others as much more predictable. 'I'm complex; you're simple.'",
    "Effort justification": "The tendency to attribute greater value to an outcome if they had to put effort into achieving it. Suffering through something makes us value it more.",
    "Risk compensation": "The tendency to take greater risks when one perceives greater safety measures are in place. Protective equipment can paradoxically lead to riskier behaviour.",
    "Hyperbolic discounting": "The tendency to give stronger preference to more immediate payoffs relative to later payoffs, with the discount rate decreasing over time. We are impatient now but patient about the future.",
    "Appeal to novelty": "The assumption that something new is automatically better than something older. Innovation is equated with improvement without evidence.",
    "Identifiable victim effect": "The tendency for people to offer more help to a specific identified individual in need than to a large anonymized group of people in need. Statistics about many don't move us; a face does.",
    "Sunk cost fallacy": "The tendency to continue a behaviour or endeavour due to previously invested resources (time, money, effort) rather than future value. Past investment irrationally drives future decisions.",
    "Escalation of commitment": "The tendency to continue a course of action even when feedback suggests it is failing, in order to justify previous investments. Doubling down on a bad bet.",
    "Loss aversion": "The tendency to prefer avoiding losses over acquiring equivalent gains. Losing $100 feels worse than winning $100 feels good.",
    "IKEA effect": "The tendency for people to place a disproportionately high value on objects they partially created. Assembling furniture yourself makes it feel more valuable.",
    "Generation effect": "Information that is self-generated is remembered better than information that is read passively. Active production creates stronger memory traces than passive reception.",
    "Zero-risk bias": "The preference for reducing a small risk to zero over a greater reduction of a larger risk. Eliminating one danger entirely feels more satisfying than reducing a bigger danger more.",
    "Disposition effect": "The tendency to sell assets that have gained in value but keep assets that have declined. Investors lock in gains too early and hold losses too long.",
    "Unit bias": "The tendency to eat or consume one standard unit of an item (one portion, one serving, one piece), regardless of how large or small that unit actually is. Portion size drives consumption.",
    "Pseudocertainty effect": "The tendency to make risk-averse choices in a domain if a positive outcome is certain, regardless of the probability of the positive outcome being achieved. False certainty reduces rational risk evaluation.",
    "Endowment effect": "The tendency to assign more value to things merely because you own them. Owning an object makes you rate it higher than the same object you do not own.",
    "Backfire effect": "The tendency to react to disconfirming evidence by strengthening one's original belief. Corrections can make misconceptions more entrenched rather than less.",
    "Reactance": "The urge to do the opposite of what someone wants you to do out of a need to maintain one's freedom of choice. Restrictions make the restricted option more attractive.",
    "Reverse psychology": "The strategy of advocating for the opposite of what one actually desires, exploiting reactance. By appearing to restrict freedom, one motivates the desired behaviour.",
    "Decoy effect": "The tendency for preferences between two options to change when a third, asymmetrically dominated option is introduced. The decoy makes one of the original options look more attractive.",
    "Social comparison bias": "The tendency to have positive feelings toward individuals who are less competent than oneself and negative feelings toward those who are more competent. Upward comparisons threaten self-esteem.",
    "Status quo bias": "The tendency to prefer the current state of affairs, treating any change from the baseline as a loss. Inertia overweights the status quo relative to alternatives.",
    "Ambiguity bias": "The tendency to avoid options whose probabilities are unknown, in favour of options where probabilities are known. Known risk is preferred over unknown uncertainty.",
    "Information bias": "The tendency to seek information even when it cannot affect action. More information is assumed to always lead to better decisions, even when it's irrelevant.",
    "Belief bias": "The tendency to evaluate the logical strength of an argument based on the believability of its conclusion rather than on whether it is logically valid. We accept invalid arguments with true conclusions.",
    "Rhyme as reason effect": "The tendency to judge rhyming statements as more accurate or truthful than non-rhyming statements. Rhyme creates a sense of fluency that is misattributed to truth.",
    "Law of Triviality": "The tendency to give disproportionate weight to trivial issues while ignoring complex but important ones. Committees discuss bike sheds for hours but approve nuclear plants in minutes.",
    "Delmore effect": "The tendency to set more specific and concrete goals for unimportant targets than for important ones. People spend more effort specifying trivial goals than critical ones.",
    "Conjunction fallacy": "The tendency to assume that specific conditions are more probable than a single general one. Adding more detail makes a story feel more plausible, though it is statistically less likely.",
    "Occams razor": "The principle that among competing hypotheses, the one with the fewest assumptions should be selected. Simpler explanations are preferred over complex ones when evidence is equal.",
    "Less-is-better effect": "The tendency to prefer a smaller set to a larger set when assessed separately, but not together. Evaluated alone, quality beats quantity; evaluated together, quantity wins.",
    "Misattribution of memory": "Correctly remembering information but incorrectly identifying the source of that information. The content is accurate but the attribution to a context or person is wrong.",
    "Cryptomnesia": "When a forgotten memory returns without being recognised as such, causing the person to believe it is something new and original. Unconscious plagiarism of one's own past experiences.",
    "False memory": "The phenomenon where someone recalls something that did not happen or happened differently from how it actually did. Memory is reconstructive, not a perfect recording.",
    "Suggestibility": "The quality of being inclined to accept and act on suggestions from others. Suggestible individuals are particularly vulnerable to implanted false memories.",
    "Spacing effect": "The phenomenon whereby learning is more effective when studying is spread out over time rather than massed together. Distributed practice produces stronger long-term retention.",
    "Implicit associations": "Unconscious attitudes or stereotypes that affect behavior and judgments without conscious awareness or intentional control. These associations are measured by response time differences.",
    "Prejudice": "A preconceived opinion that is not based on reason or actual experience, often directed against a particular group. Prejudices involve unfair attitudes that resist contradicting evidence.",
    "Fading affect bias": "The phenomenon whereby emotions associated with unpleasant memories fade more quickly than emotions associated with pleasant memories. Negative feelings are forgotten faster, contributing to rosy retrospection.",
    "Peak_end_rule": "The tendency to judge an experience largely based on how it felt at its most intense point and at its end, rather than by the sum or average of each moment. Duration is discounted.",
    "Leveling and sharpening": "Memory distortions in which some details are lost over time (leveling) while other details become exaggerated (sharpening). Stories become simpler and more dramatic with retelling.",
    "Misinformation effect": "When a person's recall of episodic memories becomes less accurate because of post-event information. Leading questions or false suggestions corrupt the original memory.",
    "Duration neglect": "The finding that the duration of a painful or pleasurable experience has little influence on the memory of it. The peak and the end matter far more than how long something lasted.",
    "Serial recall effect": "The tendency for items at the beginning and end of a sequence to be recalled more easily than those in the middle. Primacy and recency effects combine in this serial position curve.",
    "Modality effect": "The tendency for the last few items of a list to be better remembered when they are heard rather than read. Auditory presentation gives a stronger recency boost.",
    "Memory inhibition": "The ability of new information to impair the recall of old information. Retrieval of one memory can suppress related competing memories.",
    "Primacy effect": "The tendency for the first items in a list to be better remembered than subsequent items. Early items receive more rehearsal and are encoded into long-term memory.",
    "Recency effect": "The tendency for the most recently presented items in a list to be remembered best. Recent items are still in active working memory at the time of recall.",
    "Serial position effect": "The combined tendency to recall the first and last items in a series best and the middle items worst. Primacy and recency effects together create a U-shaped recall curve.",
    "Suffix effect": "The reduction in the recency effect caused by adding an extraneous item at the end of a list. The suffix item displaces the last meaningful items from working memory.",
    "Levels of processing effect": "Memory retention is better when information is processed more deeply and meaningfully. Semantic processing creates stronger memory traces than shallow phonetic processing.",
    "Testing effect": "The repeated testing of information improves long-term retention more effectively than repeated studying. Retrieval practice strengthens memory better than re-encoding.",
    "Absent-mindedness": "The failure to encode information because attention is elsewhere at the time of the event. Inattention during encoding leads to subsequent forgetting.",
    "Next-in-line effect": "The tendency for people to forget what the person directly before them in a sequence said because they were focused on preparing their own contribution. Self-concern disrupts encoding.",
    "Tip of the tongue phenomenon": "The state of being certain that you know a word or name but failing to recall it fully, with partial recall often available. Retrieval is partially successful but incomplete.",
    "Google effect": "The tendency to forget information that can easily be found using internet search engines. Digital access reduces motivation to encode and retain information internally.",
}

def main():
    biases = json.loads(DATA_FILE.read_text())
    updated = 0
    for bias in biases:
        name = bias["name"]
        if name in DESCRIPTIONS:
            bias["description"] = DESCRIPTIONS[name]
            updated += 1
        elif bias.get("description", "").strip() in ("Click to view external source.", ""):
            # Minimal fallback for any we missed
            bias["description"] = f"{name}: a cognitive bias that affects human judgment and decision-making in systematic, predictable ways."
            updated += 1
    DATA_FILE.write_text(json.dumps(biases, indent=2, ensure_ascii=False))
    print(f"Updated {updated}/{len(biases)} bias descriptions → {DATA_FILE}")

if __name__ == "__main__":
    main()
